### ISSUE TITLE
Re: "Write PDF data to a relational database using Amazon Textract" on Medium

### ISSUE THREAD

**Issue by 09thk05a17** [lvthillo/pdf-textract-to-rds#1]
Hi. I just move all the resources to eu-west-1, and it works. And I try the official demo of textract in my own region, and it can run also. Maybe I need to change some parameters of the template in other to fit in my own region? By the way, thanks a lot!

**Comment by lvthillo** [comment]
@09thk05a17 Can you find Textract in the console of your own region? (what was the region again)? I'm afraid Textract is not yet supported in the Hong-Kong region. It is in Asia Pacific (Sydney). Maybe you can try that one?

**Comment by lvthillo** [comment]
@09thk05a17 can you please checkout the latest changes and try again? (I found indeed a hardcoded value of the region). Thank you very much.

**Comment by 09thk05a17** [comment]
Oh, I make a silly mistake that Textract is not available in the region. However, I also find another problem, when I check the table, I think some row is missing, and some row is written repeatedly, and I make another try, the result is still the same.

Here is the log of write lambda:

09:28:10
START RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d Version: $LATEST

09:28:10
invoice_january.pdf_Job : SUCCEEDED

09:28:13
Connecting to database

09:28:13
END RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d

09:28:13
REPORT RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d Duration: 3003.16 ms Billed Duration: 3000 ms Memory Size: 128 MB Max Memory Used: 77 MB Init Duration: 552.47 ms

09:28:13
2020-04-17T09:28:13.958Z e67dd362-e4b3-4921-9ef6-314e60b1751d Task timed out after 3.00 seconds

09:29:19
START RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d Version: $LATEST

09:29:19
invoice_january.pdf_Job : SUCCEEDED

09:29:21
Connecting to database

09:29:21
Succesful connection!

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-02', 'Python Bug Fixing', '45.00', '5.00', '225.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-02', 'Amazon Web Services Support', '65.00', '3.00', '195.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-03', 'Architectura Design', '80.00', '8.00', '640.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-04', 'CI/CD', '70.00', '8.00', '560.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-07', 'Amazon Web Services Support', '65.00', '4.00', '260.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-07', 'CI/CD', '70.00', '4.00', '280.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-08', 'Python Bug Fixing', '45.00', '6.00', '270.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-08', 'Java Development', '50.00', '2.00', '100.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-09', 'Architectural Design', '80.00', '3.00', '240.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-09', 'Amazon Web Services Support', '65.00', '5.00', '325.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-09', 'CI/CD', '70.00', '8.00', '560.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-10', 'Kubernetes Support', '75.00', '3.00', '225.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-10', 'Python Bug Fixing', '45.00', '5.00', '225.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-11', 'Kubernetes Support', '75.00', '3.00', '225.00'])

09:29:21
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-11', 'Architectural Design', '80.00', '1.00', '80.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-11', 'Java Development', '50.00', '4.00', '200.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-14', 'Python Bug Fixing', '45.00', '5.00', '225.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-14', 'CI/CD', '70.00', '3.00', '210.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-15', 'Architectural Design', '80.00', '8.00', '640.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-16', 'Kubernetes Support', '75.00', '1.00', '75.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-16', 'CI/CD', '70.00', '2.00', '140.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-16', 'Python Bug Fixing', '45.00', '2.00', '90.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-16', 'Java Development', '50.00', '3.00', '150.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-17', 'Tool Management', '75.00', '4.00', '300.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-17', 'Java Development', '50.00', '4.00', '200.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-18', 'Architectural Design', '80.00', '3.00', '240.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-18', 'Production Deployment', '85.00', '4.00', '340.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-21', 'CI/CD', '70.00', '6.00', '420.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-21', 'Python Bug Fixing', '45.00', '2.00', '90.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-22', 'Production Deployment', '85.00', '6.00', '510.00'])

09:29:22
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-22', 'Kubernetes Support', '75.00', '2.00', '150.00'])

09:29:22
END RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d

09:29:22
REPORT RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d Duration: 3003.15 ms Billed Duration: 3000 ms Memory Size: 128 MB Max Memory Used: 39 MB

09:29:22
2020-04-17T09:29:22.143Z e67dd362-e4b3-4921-9ef6-314e60b1751d Task timed out after 3.00 seconds

09:31:10
START RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d Version: $LATEST

09:31:10
invoice_january.pdf_Job : SUCCEEDED

09:31:12
Connecting to database

09:31:13
Succesful connection!

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-02', 'Python Bug Fixing', '45.00', '5.00', '225.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-02', 'Amazon Web Services Support', '65.00', '3.00', '195.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-03', 'Architectura Design', '80.00', '8.00', '640.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-04', 'CI/CD', '70.00', '8.00', '560.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-07', 'Amazon Web Services Support', '65.00', '4.00', '260.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-07', 'CI/CD', '70.00', '4.00', '280.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-08', 'Python Bug Fixing', '45.00', '6.00', '270.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-08', 'Java Development', '50.00', '2.00', '100.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-09', 'Architectural Design', '80.00', '3.00', '240.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-09', 'Amazon Web Services Support', '65.00', '5.00', '325.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-09', 'CI/CD', '70.00', '8.00', '560.00'])

09:31:13
INSERT INTO invoices ( DATE, DESCRIPTION, RATE, HOURS, AMOUNT ) VALUES ( %s, %s, %s, %s, %s ) dict_values(['2019-01-10', 'Kubernetes Support', '75.00', '3.00', '225.00'])

09:31:13
END RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d

09:31:13
REPORT RequestId: e67dd362-e4b3-4921-9ef6-314e60b1751d Duration: 3002.25 ms Billed Duration: 3000 ms Memory Size: 128 MB Max Memory Used: 39 MB

09:31:13
2020-04-17T09:31:13.328Z e67dd362-e4b3-4921-9ef6-314e60b1751d Task timed out after 3.00 seconds

**Comment by lvthillo** [comment]
@09thk05a17  Hm did you upload the pdf only once? It's difficult to debug these logs. Or can you clean the cloudwatch logs and upload it only once again? (Also clean the database maybe because it seems some things worked but some task timed out too)?

Or can you please be a bit more specific about which row etc? You are testing in eu-west-1 now or?

**Comment by 09thk05a17** [comment]
I only upload the pdf once only. I just start my third try (still in eu-west-1). By watching the logs, I think the Write function does not fully insert all the row,  (this time it stops at row#28: 2019-01-21 CI/CD 70.00 6.00 420.00), then ends the request. After a while, it starts from the first row and inserts again (also not fully insert).

**Comment by lvthillo** [comment]
@09thk05a17 Thank you. I could reproduce it and I've increased the timeout of the lambda. For me it seems to work now. Also replaced screenshots in blog with new results. Maybe you can compare?

**Comment by 09thk05a17** [comment]
Now, I think all problem solved! If I need to modify or add some attributes (columns) in the invoice, do I need to change the read or write function? Thank you!

**Comment by lvthillo** [comment]
@09thk05a17 The write function.
